### ISSUE TITLE
domain is null

### ISSUE THREAD

**Issue by skillriver** [microsoftgraph/dotnetcore-console-sample#19]
Continuing on yesterdays project, and just adding the new userhelper and adding to program.cs, the string domain = config["domain"]; returns null in my environment, so it fails. I have to set a domain constant to get it to work.

**Comment by gavinbarron** [comment]
Hi, can you please check that you have correctly set the domain in your appsettings.json file?

I am unable to replicate this when using dotnet run.

**Comment by skillriver** [comment]
Yes, that was it. I missed that because I just continued on yesterdays solution, and then there was no domain in appsettings.json file.

**Comment by gavinbarron** [comment]
Closing as this is resolved, the domain property was introduced with at PR yesterday. 
Apologies we were a little slow getting that change onto master.

**Comment by skillriver** [comment]
Yes, thanks. Note that yesterdays blog post instructions, which I followed, still does not list domain setting in appsettings.json: https://developer.microsoft.com/en-us/graph/blogs/30daysmsgraph-day-15-microsoft-graph-in-dotnet-core-application/

Kindly regards
Jan Vidar Elven

Architect Modern Datacenter, Skill AS, MVP Enterprise Mobility, P-TSP Cloud OS & Datacenter Microsoft
Tel: +4795771854 | E-mail: jan.vidar.elven@skill.no<mailto:jan.vidar.elven@skill.no> | Web: www.skill.no<http://www.skill.no/>

«Your business – our passion»
